alias fd=fdfind

# mach cmds
alias mb="./mach build"
alias mt="./mach try fuzzy"
alias mc="./mach clang-format"
alias mch="./mach clang-format -c HEAD"
alias mch1="./mach clang-format -c HEAD~1"
alias mch2="./mach clang-format -c HEAD~2"
alias mr="./mach run"
alias mg="./mach gtest"
alias mx="./mach xpcshell-test"
alias mm="./mach mochitest"
alias mmh="./mach mochitest --headless"
alias mji="./mach jit-test"
alias mjs="./mach jstests"

alias gd="git d"
alias gau="git au"
alias gci="git ci"
alias gl="git lg"
alias gcp="git cp"
alias gcb="git cb"
alias gb="git br"
alias gso="git so"
alias gst="git st"
alias grv="git rv"

alias rrd="rr record --num-cores=12"
alias rps="rr ps"
alias rry="rr replay"
